name: Add Screenshot Comment

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  add-screenshot-comment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Find Screenshot
        id: find-screenshot
        run: |
          screenshot_file="PR-Screenshot.png"
          if [[ -f "$screenshot_file" ]]; then
            echo "::set-output name=screenshot_path::$PWD/$screenshot_file"
          else
            echo "No screenshot found."
          fi
          
      - name: Add Comment with Screenshot
        if: steps.find-screenshot.outputs.screenshot_path
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const screenshotPath = '${{ steps.find-screenshot.outputs.screenshot_path }}';
            const screenshotData = fs.readFileSync(screenshotPath, { encoding: 'base64' });
            const octokit = context.octokit;
            const owner = context.payload.repository.owner.login;
            const repo = context.payload.repository.name;
            const pullRequestNumber = context.payload.pull_request.number;
            
            octokit.issues.createComment({
              owner,
              repo,
              issue_number: pullRequestNumber,
              body: '![Screenshot](data:image/png;base64,' + screenshotData + ')'
            });
