name: Deploy 🎉🌈

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
  call-deploy:
    uses: ./.github/workflows/onlyDeploy.yml
    secrets: inherit
