name: Deploy Artifact to itch.io

on: 
  workflow_dispatch:
  workflow_call:
      inputs:
        platform:
          description: 'the unity platform'
          type: string
        channel:
          description: 'itch channel'
          type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_KEY }}
          CHANNEL: ${{ inputs.channel }}
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: ${{ inputs.platform }}